### ISSUE TITLE
Zip archive should contain one directory with the name trail

### ISSUE THREAD

**Issue by mudrd8mz** [JotaDF/moodle-format_trail#1]
It seems the plugin was affected by https://tracker.moodle.org/browse/MDLSITE-6525 and as a result, the ZIP does not contain valid root directory.

This should be easily fixable by releasing a new version.

Sorry for that.

![image](https://user-images.githubusercontent.com/85831/125066716-9cd67400-e0b3-11eb-8e20-404ee5b1e4e8.png)

**Comment by JotaDF** [comment]
Hi David,
Fixed error.

Thanks.

![Capturar](https://user-images.githubusercontent.com/46792070/125132013-141efe80-e0da-11eb-906b-a1d3e424625a.PNG)
