### ISSUE TITLE
Exception  - Unknown named parameter $size with PHP 8.0

### ISSUE THREAD

**Issue by leonstr** [JotaDF/moodle-format_trail#2]
With Moodle 3.11 and PHP 8.0, when you select **Trail format** for the course format you get exception:

_Exception - Unknown named parameter $size

More information about this error
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 704 of /course/format/lib.php: Error thrown
    line 1347 of /course/format/trail/lib.php: call to format_base->create_edit_form_elements()
    line 436 of /course/edit_form.php: call to format_trail->create_edit_form_elements()
    line 586 of /lib/formslib.php: call to course_edit_form->definition_after_data()
    line 699 of /lib/formslib.php: call to moodleform->is_validated()
    line 158 of /course/edit.php: call to moodleform->get_data()_

Other reports: [one](https://moodle.org/mod/forum/discuss.php?d=426420#p1717156), [two](https://moodle.org/plugins/format_trail#comment-72528-6135f8947c754) and [three](https://tracker.moodle.org/browse/MDL-70920?focusedCommentId=873736&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-873736).

**Comment by leonstr** [comment]
While Moodle 3.11 doesn't officially support PHP 8.0 and you don't get this exception with PHP 7.4 I think this is actually a bug in this plugin. In **course/format/trail/lib.php:format_trail->course_format_options()** there's code to set the size of text fields by setting the 'element_attributes' element of an array with the value **array('size' => 3)**. But when this is passed to **course/format/lib.php:format_base->create_edit_form_elements()** in PHP 7.4 the '3' is being treated as the first positional parameter and 'size' is discarded. But PHP 8.0 is treating this as a named parameter called **$size** which doesn't exist for **addElement()**. The 'element_attributes' is supposed to be an array containing an array of elements indexed by the attribute name, 'size' in this case. So I think it should be **array(array('size' => 3))**. You'll notice that with this change the text fields are less wide with both PHP 7.4 and PHP 8.0.

**Comment by leonstr** [comment]
Added pull request with proposed fix: https://github.com/JotaDF/moodle-format_trail/pull/3

**Comment by JotaDF** [comment]
Leon,
Thanks for the contribution.
