### ISSUE TITLE
Translation German

### ISSUE THREAD

**Issue by sanjan1809** [JotaDF/moodle-format_trail#5]
Hello!

I want to translate your very nice trail-format to german. But AMOS shows me this:

`https://lang.moodle.org/local/amos/view.php?v=31100&t=1651931890&l=de&c=format_trail`

Can you help me please?

**Comment by JotaDF** [comment]
This is a bug in AMOS, they are working to resolve it!

https://tracker.moodle.org/browse/MDLSITE-6653
